n: 4
n_samples: 200000
pop_sizes:
  pop_0:
    0: 1
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.02
      var: 0.03
      cdf: 0.01
      pdf: 0.05
      quantile: 0.02
    total_branch_length:
      mean: 0.02
      var: 0.03
    sfs:
      mean: 0.02
      m2: 0.05
