n: 6
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 0
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0031
      cdf: 0.0014
      mean: 0.002
      var: 0.0057
      quantile: 0.0035
    total_branch_length:
      mean: 0.0013
      var: 0.0039
      cosine:
        pdf: 0.0076
        cdf: 0.0015
        quantile: 0.0032
    sfs:
      mean: 0.0052
      cov: 0.034
      corr: 0.029
      cosine:
        pdf: 0.0024
        cdf: 0.0011
        quantile: 0.88
      pairwise:
        cosine:
          cdf: 0.0023
          pdf: 0.0053
