n: 2
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.9
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.004
      cdf: 0.002
      mean: 0.0044
      var: 0.012
      quantile: 0.004
    total_branch_length:
      mean: 0.0044
      var: 0.012
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
    sfs:
      mean: 0.0044
      cov: 0.012
      corr: 0.0005
      cosine:
        pdf: 0.0041
        cdf: 0.002
        quantile: 0.004
