n: 2
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.99
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0013
      cdf: 0.00062
      mean: 0.00071
      var: 0.00033
      quantile: 0.0056
    total_branch_length:
      mean: 0.00071
      var: 0.00033
      cosine:
        pdf: 0.0028
        cdf: 0.00065
        quantile: 0.0056
    sfs:
      mean: 0.00071
      cov: 0.00033
      corr: 0.0005
      cosine:
        pdf: 0.0031
        cdf: 0.00065
        quantile: 0.0056
      pairwise:
        cosine:
          cdf: 0.0006
          pdf: 0.0005
