n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
c: 5
psi: 0.7
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.0027
      var: 0.0092
    total_branch_length:
      mean: 0.0018
      var: 0.0064
    sfs:
      mean: 0.021
