n: 6
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 0
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.004
      cdf: 0.002
      mean: 0.0024
      var: 0.0095
      quantile: 0.004
    total_branch_length:
      mean: 0.002
      var: 0.0085
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
    sfs:
      mean: 0.0091
      cov: 0.06
      corr: 0.059
      cosine:
        pdf: 0.0042
        cdf: 0.002
        quantile: 0.0048
      pairwise:
        '[(1, 2), (1, 5), (2, 5)]':
          cdf: 0.002
          pdf: 0.0077
