n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.5
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.0024
      var: 0.0091
    total_branch_length:
      mean: 0.0016
      var: 0.0063
    sfs:
      mean: 0.017
