n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
c: 5
psi: 0.7
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0037
      mean: 0.0005
      var: 0.0038
      cdf: 0.0011
      quantile: 0.0033
    total_branch_length:
      mean: 0.0006
      var: 0.0028
      cosine:
        pdf: 0.015
        cdf: 0.0019
        quantile: 0.0034
    sfs:
      mean: 0.0099
      '[1, 9, 19]':
        cosine:
          pdf: 0.5
          cdf: 0.5
          quantile: 0.5
      pairwise:
        cosine:
          '[(1, 2), (1, 19), (2, 19)]':
            cdf: 0.5
            pdf: 0.5
