n:
  pop_0: 3
  pop_1: 3
num_replicates: 1000000
migration_rates:
  0:
    - [ 0, 1 ]
    - [ 1, 0 ]
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
model: standard
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02
