n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
c: 5
psi: 0.7
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      mean: 0.01
      var: 0.05
    total_branch_length:
      mean: 0.01
      var: 0.05
    sfs:
      mean: 0.02