n:
  pop_0: 1
  pop_1: 1
num_replicates: 1000000
precision: 1.0e-7
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0.1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0
pop_sizes:
  pop_0:
    0: 10000
  pop_1:
    0: 0.0001
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.02
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02
