n: 6
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.9
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0032
      cdf: 0.0017
      mean: 0.0011
      var: 0.00084
      quantile: 0.0037
    total_branch_length:
      mean: 0.00056
      var: 0.0009
      cosine:
        pdf: 0.008
        cdf: 0.0012
        quantile: 0.0037
    sfs:
      pairwise:
        cosine:
          '[(1, 2), (1, 5), (2, 5)]':
            cdf: 0.0026
            pdf: 0.0054
      mean: 0.0067
      cov: 0.034
      corr: 0.034
      cosine:
        pdf: 0.002
        cdf: 0.0024
        quantile: 0.15
