n:
  pop_0: 2
  pop_1: 2
num_replicates: 500000
seed: 102
model: beta
alpha: 1.5
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0.75
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0.75
comparisons:
  tolerance:
    jsfs:
      mean: 0.03
      var: 0.06
