n:
  pop_0: 1
  pop_1: 1
  pop_2: 1
num_replicates: 500000
seed: 7
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
  pop_2:
    0: 1
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 1
  !!python/tuple [ 'pop_0', 'pop_2' ]:
    0: 1
  !!python/tuple [ 'pop_2', 'pop_0' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_2' ]:
    0: 1
  !!python/tuple [ 'pop_2', 'pop_1' ]:
    0: 1
model: standard
comparisons:
  tolerance:
    jsfs:
      mean: 0.02
