n: 3
n_loci: 2
recombination_rate: 1
n_samples: 200000
pop_sizes:
  pop_0:
    0: 1
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.02
      var: 0.03
      loci:
        mean: 0.02
        cov: 0.05
        corr: 0.05
        pairwise:
          cosine:
            cdf: 0.03
            pdf: 0.1
    sfs2:
      mean: 0.1
