n: 4
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 1
mass_threshold: 0.7
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 1
comparisons:
  tolerance:
    sfs:
      mutation_configs: 0.02
    fsfs:
      mutation_configs: 0.02
