n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.004
      cdf: 0.002
      mean: 0.003
      var: 0.0093
      quantile: 0.004
    total_branch_length:
      mean: 0.0027
      var: 0.0084
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
    sfs:
      mean: 0.007
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.0053
      pairwise:
        '[(1, 2), (1, 4), (2, 4)]':
          cdf: 0.002
          pdf: 0.0059
