n: 4
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 1
mass_threshold: 0.7
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.5
comparisons:
  tolerance:
    sfs:
      mutation_configs: 0.1
    fsfs:
      mutation_configs: 0.1
