n: 10
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 0.01
mass_threshold: 0.999
pop_sizes:
  pop_0:
    0: 1
model: standard
comparisons:
  tolerance:
    sfs:
      mutation_configs: 0.1
    fsfs:
      mutation_configs: 0.1
