n: 3
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.004
      cdf: 0.002
      mean: 0.0038
      var: 0.011
      quantile: 0.004
    total_branch_length:
      mean: 0.0035
      var: 0.0095
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
    sfs:
      mean: 0.0059
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
      pairwise:
        '[(1, 2)]':
          cdf: 0.002
          pdf: 0.015
