n:
  pop_0: 5
  pop_1: 1
num_replicates: 500000
seed: 101
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 0.5
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0.25
model: standard
comparisons:
  tolerance:
    jsfs:
      mean: 0.03
