n: 2
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.5
comparisons:
  tolerance:
    tree_height:
      pdf: 1
      cdf: 1
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.02