n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0033
      cdf: 0.00074
      mean: 0.0013
      var: 0.0025
      quantile: 0.0031
    total_branch_length:
      mean: 0.0014
      var: 0.0028
      cosine:
        pdf: 0.0093
        cdf: 0.0016
        quantile: 0.0047
    sfs:
      mean: 0.0052
      cosine:
        pdf: 0.0032
        cdf: 0.0016
        quantile: 0.55
      pairwise:
        cosine:
          cdf: 0.0011
          pdf: 0.012
