n:
  pop_0: 6
  pop_1: 0
num_replicates: 1000000
record_migration: true
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
model: standard
comparisons:
  tolerance:
    tree_height:
      demes:
        cov: 0.01
      pdf: 1
      cdf: 1
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02
