n:
  pop_0: 2
  pop_1: 2
  pop_2: 2
num_replicates: 1000000
record_migration: true
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 3
    !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 4
    !!python/tuple [ 'pop_0', 'pop_2' ]:
    0: 1
    !!python/tuple [ 'pop_2', 'pop_0' ]:
    0: 15
    !!python/tuple [ 'pop_1', 'pop_2' ]:
    0: 6
    !!python/tuple [ 'pop_2', 'pop_1' ]:
    0: 10
pop_sizes:
  pop_0:
    0: 1.5
  pop_1:
    0: 0.5
  pop_2:
    0: 1
model: standard
comparisons:
  tolerance:
    tree_height:
      cov_demes: 0.01
      demes:
        mean: 0.01
        var: 0.02
      pdf: 0.01
      cdf: 0.3
      mean: 0.01
      var: 0.02
    total_branch_length:
      # cov_demes: 0.01 slight differences between covariance of tree height and covariance of number of lineages in demes
      demes:
        mean: 0.01
        var: 0.02
      mean: 0.01
      var: 0.02
    sfs:
      demes:
        mean: 0.015
        # var: 0.02 variance not supported by MsprimeCoalescent
      mean: 0.01
      cov: 0.02
      corr: 0.02