n: 3
n_loci: 2
recombination_rate: 1
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.5
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.004
      cdf: 0.002
      mean: 0.0028
      var: 0.0085
      loci:
        mean: 0.01
        var: 0.05
        cov: 0.014
        corr: 0.013
    total_branch_length:
      mean: 0.0026
      var: 0.0077
      loci:
        mean: 0.01
        var: 0.05
        cov: 0.013
        corr: 0.011
    #sfs:
    #  mean: 0.01
    #  var: 0.05
    #  cov: 0.05
    #  corr: 0.05
