n: 2
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.011
      cdf: 0.00072
      mean: 0.00056
      var: 0.00042
      m2: 0.05
      m3: 0.00057
      m4: 0.0012
      quantile: 0.00093
    total_branch_length:
      mean: 0.00056
      var: 0.00042
      m2: 0.05
      m3: 0.00057
      m4: 0.0012
      cosine:
        pdf: 0.0095
        cdf: 0.00072
        quantile: 0.00093
    sfs:
      mean: 0.00056
      cov: 0.00042
      corr: 0.0005
      m2: 0.02
      m3: 0.00057
      m4: 0.0012
      cosine:
        pdf: 0.0091
        cdf: 0.00072
        quantile: 0.00093
