n:
  pop_0: 2
  pop_1: 2
  pop_2: 2
num_replicates: 1000000
migration_rates:
  0:
    - [ 0, 3, 1 ]
    - [ 4, 0, 10 ]
    - [ 15, 6, 0 ]
pop_sizes:
  pop_0:
    0: 1.5
  pop_1:
    0: 0.5
  pop_2:
    0: 1
model: standard
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      pdf: 0.01
      cdf: 0.3
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02