n: 3
n_loci: 2
recombination_rate: 1
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0048
      cdf: 0.0012
      mean: 0.0013
      var: 0.0025
      loci:
        pairwise:
          cosine:
            cdf: 0.0073
            pdf: 0.015
        mean: 0.01
        var: 0.05
        cov: 0.0036
        corr: 0.0008
    total_branch_length:
      mean: 0.0012
      var: 0.0014
      loci:
        pairwise:
          cosine:
            cdf: 0.0062
            pdf: 0.013
        mean: 0.01
        var: 0.05
        cov: 0.0027
        corr: 0.00015
    #sfs:
    #  mean: 0.01
    #  var: 0.01
    #  cov: 0.02
    #  corr: 0.02
