n: 4
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0041
      cdf: 0.002
      mean: 0.0031
      var: 0.0098
      quantile: 0.004
    total_branch_length:
      mean: 0.0026
      var: 0.0089
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.004
    sfs:
      pairwise:
        '[(1, 2), (1, 3), (2, 3)]':
          cdf: 0.002
          pdf: 0.0085
      mean: 0.0086
      cosine:
        pdf: 0.004
        cdf: 0.002
        quantile: 0.0082
