n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.012
      cdf: 0.00074
      mean: 0.0013
      var: 0.0025
      quantile: 0.0012
    total_branch_length:
      mean: 0.0014
      var: 0.0028
      cosine:
        pdf: 0.012
        cdf: 0.0016
        quantile: 0.0014
    sfs:
      mean: 0.0052
      cosine:
        pdf: 0.014
        cdf: 0.0016
        quantile: 0.0053
      pairwise:
        cosine:
          '[(1, 2), (1, 4), (2, 4)]':
            cdf: 0.0016
            pdf: 0.0059
