n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
c: 5
psi: 0.7
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.0005
      var: 0.0038
    total_branch_length:
      mean: 0.0006
      var: 0.0028
    sfs:
      mean: 0.0099
