n:
  pop_0: 1
  pop_1: 1
n_loci: 2
recombination_rate: 1
num_replicates: 1000000
#record_migration: true # problems with MsprimeDistribution when recording migration with recombination; CDF changes
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 1
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.1
      mean: 0.01
      var: 0.01
      loci:
        mean: 0.01
        var: 0.02
        cov: 0.02
        corr: 0.02
      #demes:
      #  mean: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
      loci:
        mean: 0.01
        var: 0.02
        cov: 0.02
        corr: 0.02
      #demes:
      #  mean: 0.01
    #sfs:
    #  mean: 0.01
    #  var: 0.05
    #  cov: 0.05
    #  corr: 0.05