n: 4
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.7
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.012
      cdf: 0.00074
      mean: 0.0011
      var: 0.0043
      quantile: 0.0013
    total_branch_length:
      mean: 0.0008
      var: 0.0044
      cosine:
        pdf: 0.011
        cdf: 0.00096
        quantile: 0.00098
    sfs:
      mean: 0.0028
      cosine:
        pdf: 0.012
        cdf: 0.0012
        quantile: 0.0038
      pairwise:
        cosine:
          '[(1, 2), (1, 3), (2, 3)]':
            cdf: 0.0019
            pdf: 0.0072
