n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.99999999
c: 50
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0016
      cdf: 0.0011
      mean: 0.00042
      var: 9.1e-05
      quantile: 0.0058
    total_branch_length:
      mean: 0.00051
      var: 0.0011
      cosine:
        pdf: 0.0064
        cdf: 0.0013
        quantile: 0.0053
    sfs:
      mean: 0.051
      cosine:
        pdf: 0.27
        cdf: 0.003
        quantile: 0.048
      pairwise:
        cosine:
          cdf: 0.0005
          pdf: 0.0005
