n: 6
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: beta
alpha: 1.7
comparisons:
  tolerance:
    tree_height:
      pdf: 0.03
      cdf: 0.03
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.02