n: 6
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
model: dirac
psi: 0.5
c: 1
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0033
      cdf: 0.0009
      mean: 0.00012
      var: 0.0026
      quantile: 0.0015
    total_branch_length:
      mean: 0.0005
      var: 0.0015
      cosine:
        pdf: 0.0084
        cdf: 0.00057
        quantile: 0.0018
    sfs:
      mean: 0.0018
      cov: 0.086
      corr: 0.084
      cosine:
        pdf: 0.0022
        cdf: 0.00095
        quantile: 0.08
      pairwise:
        cosine:
          cdf: 0.00072
          pdf: 0.35
