n: 2
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
    1: 0.001
model: standard
comparisons:
  types:
    - ph
  tolerance:
    # hard to compare PDF and CDF here
    tree_height:
      pdf: 0.1
      cdf: 0.02
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.01
      corr: 0.02