n: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 10
    1: 1
model: standard
seed: 42
comparisons:
  tolerance:
    sfs:
      "[1, 3, 9]":
        cosine:
          pdf: 0.0047
          cdf: 0.002
          quantile: 0.0082
      pairwise:
        (1, 2):
          cdf: 0.002
          pdf: 0.011
        "[(1, 9), (4, 5), (3, 7)]":
          cdf: 0.0023
          pdf: 0.004
