n:
  pop_0: 0
  pop_1: 3
num_replicates: 1000000
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0
    100: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0
    100: 1
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 0.000001
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 20000 # very large values / short coalescence time
      cdf: 0.02
      mean: 0.01
      var: 0.1 # precision problems due to very low variance, increasing precision doesn't converge
    total_branch_length:
      mean: 0.01
      var: 0.02 # this is larger than for the tree height, so it works
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02
