n: 5
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 1
mass_threshold: 0.8
pop_sizes:
  pop_0:
    0: 1
    1: 0.001
model: standard
seed: 42
comparisons:
  tolerance:
    fsfs:
      mutation_configs: 0.004
    tree_height:
      pdf: 0.0062
      cdf: 0.002
      mean: 0.00094
      var: 0.0079
      quantile: 0.004
    total_branch_length:
      mean: 0.0011
      var: 0.0061
      cosine:
        pdf: 0.0049
        cdf: 0.002
        quantile: 0.004
    sfs:
      mutation_configs: 0.004
      mean: 0.0057
      cov: 0.061
      corr: 0.063
      theta_pi: 0.004
      theta_w: 0.004
      tajimas_d: 0.0069
      cosine:
        pdf: 0.4
        cdf: 0.002
        quantile: 0.0048
      pairwise:
        '[(1, 2), (1, 4), (2, 4)]':
          cdf: 0.0022
          pdf: 0.019
