n: 8
num_replicates: 200000
pop_sizes:
  pop_0:
    0: 1
    0.5: 5
model: standard
seed: 42
comparisons:
  tolerance:
    sfs:
      mean: 0.0035
      theta_pi: 0.00071
      theta_w: 0.00035
      tajimas_d: 0.0046
      '[1, 3, 7]':
        cosine:
          pdf: 0.088
          cdf: 0.0015
          quantile: 0.083
      pairwise:
        cosine:
          '[(1, 2), (1, 7), (2, 7)]':
            cdf: 0.0033
            pdf: 0.15
    tree_height:
      pdf: 0.03
      cdf: 0.0023
      quantile: 0.0051
    total_branch_length:
      cosine:
        pdf: 0.036
        cdf: 0.0023
        quantile: 0.0046
