n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
    1: 0.001
precision: 1.0e-9
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.1
      cdf: 2
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.03