n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
    1: 0.001
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.055
      cdf: 0.00086
      mean: 0.00032
      var: 0.0032
      quantile: 0.00033
    total_branch_length:
      mean: 0.00021
      var: 0.0017
      cosine:
        pdf: 0.0011
        cdf: 0.00033
        quantile: 0.00026
    sfs:
      mean: 0.004
      cov: 0.059
      corr: 0.06
      theta_pi: 7.6e-05
      theta_w: 0.00021
      tajimas_d: 0.0069
      cosine:
        pdf: 0.035
        cdf: 0.0019
        quantile: 0.0051
      pairwise:
        cosine:
          '[(1, 2), (1, 4), (2, 4)]':
            cdf: 0.0022
            pdf: 0.019
