n:
  pop_0: 2
  pop_1: 2
num_replicates: 1000000
#record_migration: true
pop_sizes:
  pop_0:
    0: 0.5
    1: 0.5
  pop_1:
    0: 2
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0.2
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.1
      mean: 0.01
      var: 0.05
      #demes:
      #  mean: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.05
      #demes:
      #  mean: 0.01
    sfs:
      mean: 0.01
      var: 0.05
      cov: 0.05
      corr: 0.05
      #demes:
      #  mean: 0.01
