n: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 10
    1: 1
model: standard
seed: 42
comparisons:
  tolerance:
    sfs:
      "[1, 3, 9]":
        cosine:
          pdf: 0.15
          cdf: 0.0013
          quantile: 0.016
      pairwise:
        cosine:
          (1, 2):
            cdf: 0.0011
            pdf: 0.028
          "[(1, 9), (4, 5), (3, 7)]":
            cdf: 0.0023
            pdf: 0.044
