n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 10000000
    10000000: 50000000
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.01
      cdf: 0.01
      mean: 0.01
      var: 0.02
      quantile: 0.5
    total_branch_length:
      mean: 0.01
      var: 0.02
      cosine:
        pdf: 0.5
        cdf: 0.5
        quantile: 0.5
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02
      cosine:
        pdf: 0.5
        cdf: 0.5
        quantile: 0.5
      pairwise:
        cosine:
          cdf: 0.5
          pdf: 0.5
