n:
  pop_0: 1
  pop_1: 1
num_replicates: 1000000
record_migration: true
migration_rates:
  ? !!python/tuple
  - 'pop_0'
  - 'pop_1'
  : 0: 0
    100: 1
  ? !!python/tuple
  - 'pop_1'
  - 'pop_0'
  : 0: 0
    100: 1
pop_sizes:
  pop_0:
    0: 1
  pop_1:
    0: 1
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      demes:
        cov: 0.014
      pdf: 0.004
      cdf: 0.002
      mean: 9.5e-05
      var: 0.013
    total_branch_length:
      mean: 9.5e-05
      var: 0.013
    sfs:
      mean: 9.5e-05
      cov: 0.013
      corr: 0.0005
