n:
  pop_0: 3
n_loci: 2
recombination_rate: 1.0
num_replicates: 200000
seed: 54
pop_sizes:
  pop_0:
    0: 1
    0.5: 0.3
    1.5: 2.0
model: dirac
psi: 0.5
c: 1
comparisons:
  tolerance:
    sfs2:
      pairwise:
        '(1, 2)':
          cdf: 0.0036
          pdf: 0.034
      mean: 0.0026
