n:
  pop_0: 2
  pop_1: 2
  pop_2: 2
num_replicates: 1000000
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 3
  !!python/tuple [ 'pop_0', 'pop_2' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 4
  !!python/tuple [ 'pop_1', 'pop_2' ]:
    0: 10
  !!python/tuple [ 'pop_2', 'pop_0' ]:
    0: 15
  !!python/tuple [ 'pop_2', 'pop_1' ]:
    0: 6
pop_sizes:
  pop_0:
    0: 1.5
    0.3: 2.4
    1.1: 0.3
  pop_1:
    0: 0.5
    0.1: 0.6
    0.45: 0.7
  pop_2:
    0: 0.02
    1: 0.01
    2: 1.4
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.2
      mean: 0.01
      var: 0.02
      demes:
        mean: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.02
      demes:
        mean: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.05
      demes:
        mean: 0.01
