n: 5
num_replicates: 1000000
pop_sizes:
  - 1
  - 0.01
  - 1
times:
  - 0
  - 0.3
  - 1
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02