n: 5
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 1
mass_threshold: 0.9
pop_sizes:
  pop_0:
    0: 1
    0.3: 0.01
    1: 1
model: standard
seed: 42
comparisons:
  tolerance:
    fsfs:
      mutation_configs: 0.039
    tree_height:
      pdf: 0.011
      cdf: 0.0008
      mean: 3.1e-05
      var: 0.012
      quantile: 4.6e-05
    total_branch_length:
      mean: 0.00015
      var: 0.00033
      cosine:
        pdf: 0.00027
        cdf: 9.1e-05
        quantile: 0.00015
    sfs:
      mutation_configs: 0.042
      mean: 0.0011
      cov: 0.017
      corr: 0.018
      theta_pi: 7.6e-05
      theta_w: 0.00015
      tajimas_d: 0.00018
      cosine:
        pdf: 0.028
        cdf: 0.0017
        quantile: 0.003
      pairwise:
        cosine:
          '[(1, 2), (1, 4), (2, 4)]':
            cdf: 0.011
            pdf: 0.13
