n:
  pop_0: 2
  pop_1: 2
  pop_2: 1
num_replicates: 500000
seed: 106
pop_sizes:
  pop_0:
    0: 1
    0.5: 0.5
  pop_1:
    0: 1.5
  pop_2:
    0: 0.8
    0.7: 1.5
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 1
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0.5
  !!python/tuple [ 'pop_1', 'pop_2' ]:
    0: 0.5
  !!python/tuple [ 'pop_2', 'pop_1' ]:
    0: 1
model: standard
comparisons:
  tolerance:
    jsfs:
      mean: 0.04
