n:
  pop_0: 2
  pop_1: 2
  pop_2: 2
num_replicates: 1000000
#record_migration: true
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0.0003
  !!python/tuple [ 'pop_0', 'pop_2' ]:
    0: 0.0001
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 0.0004
  !!python/tuple [ 'pop_1', 'pop_2' ]:
    0: 0.0001
  !!python/tuple [ 'pop_2', 'pop_0' ]:
    0: 0.00015
  !!python/tuple [ 'pop_2', 'pop_1' ]:
    0: 0.0006
pop_sizes:
  pop_0:
    0: 15000
    3000: 24000
    11000: 3000
  pop_1:
    0: 5000
    10000: 6000
    45000: 7000
  pop_2:
    0: 200
    10000: 100
    20000: 14000
model: beta
alpha: 1.5
comparisons:
  tolerance:
    tree_height:
      pdf: 0.01
      cdf: 0.2
      mean: 0.01
      var: 0.02
      #demes:
      #  mean: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.02
      #demes:
      #  mean: 0.01
    sfs:
      mean: 0.01
      cov: 0.07
      corr: 0.07
      #demes:
      #  mean: 0.01
    fsfs:
      mean: 0.01
      cov: 0.07
      corr: 0.07
      #demes:
      #  mean: 0.01
