n: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1
    0.3: 0.01
    1: 1
model: standard
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      pdf: 0.2
      cdf: 2
      mean: 0.01
      var: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
    sfs:
      mean: 0.01
      cov: 0.02
      corr: 0.02