n: 10
num_replicates: 1000000
pop_sizes:
  - 1.2
  - 10
  - 0.8
  - 10
times:
  - 0
  - 0.3
  - 1
  - 1.4
model: standard
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.02