n: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1.2
    0.3: 10
    1: 0.8
    1.4: 10
model: standard
comparisons:
  types:
    - ph
  tolerance:
    tree_height:
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05
      corr: 0.02