n: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 1.2
    0.3: 10
    1: 0.8
    1.4: 10
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.012
      cdf: 0.00095
      mean: 0.0021
      var: 0.0076
      quantile: 0.0019
    total_branch_length:
      mean: 0.0016
      var: 0.0065
      cosine:
        pdf: 0.022
        cdf: 0.00069
        quantile: 0.0013
    sfs:
      mean: 0.011
      cov: 0.038
      corr: 0.031
      theta_pi: 0.00096
      theta_w: 0.0016
      tajimas_d: 0.011
      '[1, 4, 9]':
        cosine:
          pdf: 0.027
          cdf: 0.0015
          quantile: 0.0095
