n: 2
num_replicates: 1000000
simulate_mutations: true
mutation_rate: 1
mass_threshold: 0.9
pop_sizes:
  pop_0:
    0: 1.2
    0.3: 10
    1: 0.8
    1.4: 10
model: standard
seed: 42
comparisons:
  tolerance:
    fsfs:
      mutation_configs: 0.092
    tree_height:
      pdf: 0.034
      cdf: 0.00062
      mean: 0.0023
      var: 0.0051
      quantile: 0.0021
    total_branch_length:
      mean: 0.0023
      var: 0.0051
      cosine:
        pdf: 0.049
        cdf: 0.0037
        quantile: 0.0036
    sfs:
      mutation_configs: 0.092
      pairwise:
        cosine: {}
      mean: 0.0023
      cov: 0.0051
      corr: 0.0005
      cosine:
        pdf: 0.021
        cdf: 0.0037
        quantile: 0.0036
