n:
  pop_0: 2
  pop_1: 2
n_loci: 2
recombination_rate: 5
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 2
    0.1: 0.1
    0.5: 0.5
  pop_1:
    0: 1
    0.3: 2
    0.94: 0.1
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0.2
    0.1: 0.1
    0.5: 0.33
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 1
    0.3: 0.5
    0.94: 0.124
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.1
      mean: 0.01
      var: 0.02
      loci:
        mean: 0.01
        var: 0.02
        cov: 0.02
        corr: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.02
      loci:
        mean: 0.01
        var: 0.02
        cov: 0.02
        corr: 0.02
    #sfs:
    #  mean: 0.01
    #  var: 0.05
    #  cov: 0.05
    #  corr: 0.05