n:
  pop_0: 20
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 2
    1.1: 0.3
    3.5: 0.5
    4.2: 8
    7.5: 2.3
model: standard
seed: 42
comparisons:
  tolerance:
    tree_height:
      mean: 0.00029
      var: 0.015
    total_branch_length:
      mean: 0.00045
      var: 0.0041
    sfs:
      mean: 0.0074
