n:
  pop_0: 1
  pop_1: 1
n_loci: 2
recombination_rate: 1
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 2
    1: 0.3
  pop_1:
    0: 1
    0.2: 1.3
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 0.5
    0.3: 0.8
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 2
    0.6: 1.6
model: standard
comparisons:
  tolerance:
    tree_height:
      pdf: 0.02
      cdf: 0.1
      mean: 0.01
      var: 0.05
      loci:
        mean: 0.01
        var: 0.05
        cov: 0.02
        corr: 0.02
    total_branch_length:
      mean: 0.01
      var: 0.05
      loci:
        mean: 0.01
        var: 0.05
        cov: 0.02
        corr: 0.02
    #sfs:
    #  mean: 0.01
    #  var: 0.05
    #  cov: 0.05
    #  corr: 0.05