n:
  pop_0: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 2
    1.1: 0.3
    3.5: 0.5
    4.2: 8
    7.5: 2.3
model: dirac
c: 5
psi: 0.7
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.013
      mean: 0.00039
      var: 0.0037
      cdf: 0.0011
      quantile: 0.00051
    total_branch_length:
      mean: 0.0011
      var: 0.0012
      cosine:
        pdf: 0.0011
        cdf: 0.00042
        quantile: 0.0011
    sfs:
      mean: 0.007
      '[1, 4, 9]':
        cosine:
          pdf: 0.017
          cdf: 0.0011
          quantile: 0.0037
