n:
  pop_0: 10
num_replicates: 1000000
pop_sizes:
  pop_0:
    0: 2
    1.1: 0.3
    3.5: 0.5
    4.2: 8
    7.5: 2.3
model: beta
alpha: 1.5
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0016
      mean: 0.0011
      var: 0.008
      cdf: 0.0013
      quantile: 0.0036
    total_branch_length:
      mean: 0.00062
      var: 0.0025
      cosine:
        pdf: 0.0045
        cdf: 0.0012
        quantile: 0.0039
    sfs:
      mean: 0.0055
      '[1, 4, 9]':
        cosine:
          pdf: 0.0063
          cdf: 0.0014
          quantile: 0.039
