n:
  pop_0: 6
  pop_1: 4
num_replicates: 10000000
#record_migration: true
migration_rates:
  !!python/tuple [ 'pop_0', 'pop_1' ]:
    0: 3
    0.4: 2.5
  !!python/tuple [ 'pop_1', 'pop_0' ]:
    0: 6.6
    3: 1.5
pop_sizes:
  pop_0:
    0: 1.5
    0.3: 2.4
    1.1: 0.3
  pop_1:
    0: 0.5
    0.1: 0.6
    0.45: 0.7
model: beta
alpha: 1.5
seed: 42
comparisons:
  tolerance:
    tree_height:
      pdf: 0.0013
      cdf: 0.00064
      mean: 0.00076
      m2: 0.01
      m3: 0.0036
      m4: 0.0068
      var: 0.0033
      #demes:
      #  mean: 0.01
    total_branch_length:
      mean: 0.00049
      m2: 0.01
      m3: 0.0019
      m4: 0.0033
      var: 0.0026
      #demes:
      #  mean: 0.01
    sfs:
      mean: 0.0037
      m3: 0.019
      m4: 0.036
      cov: 19
      corr: 19
      #demes:
      #  mean: 0.01
    fsfs:
      mean: 0.0034
      cov: 0.026
      #demes:
      #  mean: 0.01
