n: 5
num_replicates: 1000000
pop_sizes:
  - 1
  - 0.001
times:
  - 0
  - 1
comparisons:
  types:
    - ph
  tolerance:
    # hard to compare PDF and CDF here
    tree_height:
      mean: 0.01
      var: 0.01
    total_branch_length:
      mean: 0.01
      var: 0.01
    sfs:
      mean: 0.01
      cov: 0.05