name: base-phase-type-theory
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - msprime
  - sympy
  - jsonpickle
  - mpmath
  - tqdm
  - multiprocess
  - pyyaml
  - pytest-xdist
  - pip
  - pip:
    - pytest-pycharm