name: dev-phasegen
channels:
  - conda-forge
dependencies:
  - python=3.10
  - msprime
  - tensorflow
  - statsmodels
  - python-graphviz
  - pydot
  - jupyterlab
  - jupyter
  - pip
  - pip:
    - fastdfe
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm
    - -r requirements_testing.txt