name: dev-phasegen
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - msprime
  - sympy
  - jsonpickle
  - tqdm
  - multiprocess
  - pyyaml
  - pytest-xdist
  - pip
  - pip:
    - fastdfe
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm