name: dev-phasegen
channels:
  - conda-forge
dependencies:
  - python=3.12
  - dadi
  - numba
  - graphviz
  - python-graphviz
  - r-base
  - r-reticulate
  - r-devtools
  - r-irkernel
  - jupyterlab
  - jupyter
  - pip
  - pip:
    - msprime
    - stdpopsim
    - moments-popgen
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-sugar
    - pytest-pycharm
    # paths relative to .snakemake/conda, where snakemake copies this file before creating the env (--use-conda)
    # and where a copy must be placed to create or update the env by hand
    - -r ../../envs/requirements_testing.txt
    - -e ../..
